-- no need to add .lua
require("ade.plugins-setup")
require("ade.core.options")
require("ade.core.keymaps")
require("ade.core.colorscheme")
require("ade.plugins.comment")
require("ade.plugins.nvim-tree")
require("ade.plugins.lualine")
require("ade.plugins.telescope")
require("ade.plugins.nvim-cmp")
require("ade.plugins.lsp.mason")
require("ade.plugins.lsp.lspconfig")
require("ade.plugins.lsp.lspsaga")
require("ade.plugins.autopairs")
require("ade.plugins.treesitter")
require("ade.plugins.gitsigns")
